{
 "title": "Twitter account stat",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "username", "query": { "query": "twitter_followers" } }
  ]
 },
 "panels": [
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitter_followers{username=\"$username\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Likes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitter_tweet_like_count{username=\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Followers last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(twitter_followers{username=\"$username\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quotes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitter_tweet_quote_count{username=\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitter_tweet_reply_count{username=\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retweets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitter_tweet_retweet_count{username=\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tweets last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(twitter_tweets{username=\"$username\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Likes 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "delta(twitter_tweet_like_count{username=\"$username\"}[24h]) > 0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Tweets stat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(twitter_tweet_like_count{username=\"$username\"})",
     "legendFormat": "Likes"
    },
    {
     "expr": "sum(twitter_tweet_quote_count{username=\"$username\"})",
     "legendFormat": "Quotes"
    },
    {
     "expr": "sum(twitter_tweet_reply_count{username=\"$username\"})",
     "legendFormat": "Replies"
    },
    {
     "expr": "sum(twitter_tweet_retweet_count{username=\"$username\"})",
     "legendFormat": "Retweets"
    }
   ]
  },
  {
   "title": "Tweets likes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitter_tweet_like_count{username=\"$username\"} > 0",
     "legendFormat": "Tweet: {{id}}"
    }
   ]
  },
  {
   "title": "Tweets Retweets",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitter_tweet_retweet_count{username=\"$username\"} > 0",
     "legendFormat": "Tweet: {{id}}"
    }
   ]
  },
  {
   "title": "Tweets Replies",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitter_tweet_reply_count{username=\"$username\"} > 0",
     "legendFormat": "Tweet: {{id}}"
    }
   ]
  },
  {
   "title": "Tweets Quotes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitter_tweet_quote_count{username=\"$username\"} > 0",
     "legendFormat": "Tweet: {{id}}"
    }
   ]
  },
  {
   "title": "Follwers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "twitter_followers{username=\"$username\"}",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}