{
 "title": "Twitter common",
 "panels": [
  {
   "title": "Likes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(username) (twitter_tweet_like_count) > 0",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Retweets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(username) (twitter_tweet_retweet_count) > 0",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Replies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(username) (twitter_tweet_reply_count) > 0",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Quotes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(username) (twitter_tweet_quote_count) > 0",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Todays followers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(twitter_followers[24h]) > 0",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Todays tweets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "delta(twitter_tweets[24h]) > 0", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "twitter_followers", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Total tweets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "twitter_tweets", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Followers last 24H",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "delta(twitter_followers[24h])", "legendFormat": "{{username}}" }
   ]
  }
 ]
}