<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GRPC\Twitter\GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2010a0d6d6573736167652e70726f746f120b747769747465722e64746f22180a0a41646452657175657374120a0a026964180120012809221d0a0b416464526573706f6e7365120e0a06737461747573180120012808221b0a0d52656d6f766552657175657374120a0a02696418012001280922200a0e52656d6f7665526573706f6e7365120e0a06737461747573180120012808220c0a0a416c6c52657175657374221a0a0b416c6c526573706f6e7365120b0a03696473180120032809422aca020c475250435c54776974746572e20218475250435c547769747465725c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

