<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GRPC\Twitter\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GRPC\Twitter\GPBMetadata\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c020a0d736572766963652e70726f746f12077477697474657232cd010a0e5477697474657253657276696365123a0a0341646412172e747769747465722e64746f2e416464526571756573741a182e747769747465722e64746f2e416464526573706f6e7365220012430a0652656d6f7665121a2e747769747465722e64746f2e52656d6f7665526571756573741a1b2e747769747465722e64746f2e52656d6f7665526573706f6e73652200123a0a03416c6c12172e747769747465722e64746f2e416c6c526571756573741a182e747769747465722e64746f2e416c6c526573706f6e73652200422aca020c475250435c54776974746572e20218475250435c547769747465725c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

