<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: service.proto

namespace GRPC\Twitter;

use Spiral\RoadRunner\GRPC;

interface TwitterServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "twitter.TwitterService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \GRPC\Twitter\AddRequest $in
    * @return \GRPC\Twitter\AddResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Add(GRPC\ContextInterface $ctx, \GRPC\Twitter\AddRequest $in): \GRPC\Twitter\AddResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \GRPC\Twitter\RemoveRequest $in
    * @return \GRPC\Twitter\RemoveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Remove(GRPC\ContextInterface $ctx, \GRPC\Twitter\RemoveRequest $in): \GRPC\Twitter\RemoveResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \GRPC\Twitter\AllRequest $in
    * @return \GRPC\Twitter\AllResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function All(GRPC\ContextInterface $ctx, \GRPC\Twitter\AllRequest $in): \GRPC\Twitter\AllResponse;
}
